export const mockItemData =[
  {
    createdAt: '2024-04-23T15:34:11.689Z',
    title: 'Bespoke Soft Soap',
    image: 'https://loremflickr.com/640/480/food',
    price: '504.00',
    description: 'The Football Is Good For Training And Recreational Purposes',
    isNew: true,
    isHot: false,
    isVegetarian: true,
    id: '1',
  },
  {
    createdAt: '2024-04-24T02:27:26.226Z',
    title: 'Fantastic Metal Hat',
    image: 'https://loremflickr.com/640/480/food',
    price: '803.00',
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    isNew: true,
    isHot: true,
    isVegetarian: true,
    id: '2',
  },
  {
    createdAt: '2024-04-23T23:33:29.876Z',
    title: 'Luxurious Concrete Bacon',
    image: 'https://loremflickr.com/640/480/food',
    price: '520.00',
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    isNew: false,
    isHot: true,
    isVegetarian: true,
    id: '3',
  },
  {
    createdAt: '2024-04-24T02:43:50.706Z',
    title: 'Unbranded Metal Chips',
    image: 'https://loremflickr.com/640/480/food',
    price: '143.00',
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    isNew: false,
    isHot: false,
    isVegetarian: false,
    id: '4',
  },
  {
    createdAt: '2024-04-23T15:43:56.714Z',
    title: 'Ergonomic Concrete Chips',
    image: 'https://loremflickr.com/640/480/food',
    price: '200.00',
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    isNew: false,
    isHot: false,
    isVegetarian: true,
    id: '5',
  },
  {
    createdAt: '2024-04-24T02:22:44.305Z',
    title: 'Fantastic Soft Computer',
    image: 'https://loremflickr.com/640/480/food',
    price: '658.00',
    description:
      'Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support',
    isNew: false,
    isHot: true,
    isVegetarian: false,
    id: '6',
  },
  {
    createdAt: '2024-04-24T05:42:34.583Z',
    title: 'Oriental Soft Car',
    image: 'https://loremflickr.com/640/480/food',
    price: '869.00',
    description:
      'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    isNew: false,
    isHot: true,
    isVegetarian: true,
    id: '7',
  },
  {
    createdAt: '2024-04-23T09:55:29.710Z',
    title: 'Oriental Frozen Hat',
    image: 'https://loremflickr.com/640/480/food',
    price: '432.00',
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    isNew: false,
    isHot: true,
    isVegetarian: false,
    id: '8',
  },
  {
    createdAt: '2024-04-23T12:17:31.372Z',
    title: 'Handcrafted Bronze Car',
    image: 'https://loremflickr.com/640/480/food',
    price: '495.00',
    description: 'The Football Is Good For Training And Recreational Purposes',
    isNew: true,
    isHot: false,
    isVegetarian: true,
    id: '9',
  },
  {
    createdAt: '2024-04-24T02:13:34.107Z',
    title: 'Refined Bronze Chicken',
    image: 'https://loremflickr.com/640/480/food',
    price: '182.00',
    description: 'The Football Is Good For Training And Recreational Purposes',
    isNew: false,
    isHot: true,
    isVegetarian: true,
    id: '10',
  },
  {
    createdAt: '2024-04-23T11:03:19.887Z',
    title: 'Licensed Metal Hat',
    image: 'https://loremflickr.com/640/480/food',
    price: '148.00',
    description:
      'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    isNew: true,
    isHot: true,
    isVegetarian: false,
    id: '11',
  },
  {
    createdAt: '2024-04-23T19:41:08.145Z',
    title: 'Refined Metal Chicken',
    image: 'https://loremflickr.com/640/480/food',
    price: '181.00',
    description:
      'The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality',
    isNew: true,
    isHot: true,
    isVegetarian: false,
    id: '12',
  },
  {
    createdAt: '2024-04-23T22:22:41.197Z',
    title: 'Unbranded Metal Gloves',
    image: 'https://loremflickr.com/640/480/food',
    price: '432.00',
    description:
      'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    isNew: false,
    isHot: false,
    isVegetarian: false,
    id: '13',
  },
  {
    createdAt: '2024-04-23T15:32:11.784Z',
    title: 'Modern Plastic Shirt',
    image: 'https://loremflickr.com/640/480/food',
    price: '73.00',
    description:
      'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    isNew: true,
    isHot: true,
    isVegetarian: false,
    id: '14',
  },
  {
    createdAt: '2024-04-23T14:33:25.527Z',
    title: 'Sleek Concrete Keyboard',
    image: 'https://loremflickr.com/640/480/food',
    price: '813.00',
    description:
      'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    isNew: false,
    isHot: false,
    isVegetarian: true,
    id: '15',
  }
];
